### ISSUE TITLE
Why does CommandListener.java exist?

### ISSUE THREAD

**Issue by jd07159** [rossnoah/PerPlayerKit#6]
What is the purpose of detecting `"/ "` in this code?

**Comment by rossnoah** [comment]
Leaving a space after a command like `"/ "` can be used to bypass blocking commands with some other plugins. I believe this was added to prevent bypassing command restrictions created in WorldGuard. It should probably be removed or at the very least have a config option added.

**Comment by rossnoah** [comment]
Added config here https://github.com/rossnoah/PerPlayerKit/commit/9cbd46341ec2f31435430d84200fc2a8a464ad4d. You can get a build with this from the Jenkins.
